### ISSUE TITLE
2101 and 2103 TODOs

### ISSUE THREAD

**Issue by jjlee050** [CS2103-AY1819S1-W14-1/main#130]
### TODO list.

*CS2101*
- [x] OP2 Slides (Deadline: )
- [ ] Project Portfolio Page (Deadline: )

*CS2103T*
- [ ] Document User Guide (Deadline: )
- [ ] Document Developer Guide (Deadline: )
- [ ] Ensure that all features are working and have pass/fail test cases. (Deadline: )
- [ ] Prep product demo. (Deadline: )

Comment below if you have any.

**Comment by jjlee050** [comment]
User Guide format:
1. Introduction
2. About
3.

**Comment by jjlee050** [comment]
Developer Guide Format:

1.  Introduction
2. About
3.

**Comment by jjlee050** [comment]
OP2 Slides Order:
1. 
2. 
3. 
4. 
5.

**Comment by jjlee050** [comment]
Product Demo Order:
1. Joseph: Login, Add Patient
2. Jack: Enqueue
3. Aaron: Add medicine (Remove medicine if you can)
4. Sophia: Add appointment
5. Arsalan: Analytics
